### ISSUE TITLE
Basemap and color scheme

### ISSUE THREAD

**Issue by chrispappas007** [chrispappas007/kyarch#2]
I'm using a terrain basemap, because archaeologists love terrain maps. BUT, I'm wondering if its too much green now with my color scheme and if it looks muddy. Thoughts?

**Comment by rgdonohue** [comment]
I agree it may be better if it's more of a grayscale terrain map, in terms of complimenting your symbology in a design sense. 

You could offer a layer toggle as well, for those who want to switch to the terrain (but perhaps have the map load on a lighter gray basemap for the initial visual effect).

Or even something like contours: [https://www.mapbox.com/gallery/#map-8](https://www.mapbox.com/gallery/#map-8)
