### ISSUE TITLE
Font weight

### ISSUE THREAD

**Issue by chrispappas007** [chrispappas007/kyarch#4]
is the font in the sidebar bold enough? Specifically, look at Historic.

**Comment by rgdonohue** [comment]
Yeah, it's tough there in the dark blue. You could try playing with different saturation levels across the spectrum there:
![image](https://user-images.githubusercontent.com/1952205/30396308-6e995d42-9886-11e7-85aa-6b582dc597c2.png)

See [this commit](https://github.com/chrispappas007/kyarch/commit/bc8b6487168f4a81e6ee6efb77a8deb2b25b7e8b)

**Comment by chrispappas007** [comment]
tweaked but that definitely works better
