### ISSUE TITLE
https

### ISSUE THREAD

**Issue by chrispappas007** [chrispappas007/kyarch#5]
I believe you said that in order for github pages host our webpages our links needed to be https. for google and jquery, can I just add the 's'?

**Comment by rgdonohue** [comment]
Sometimes you can just stick in an `s` but also better to double check with the CDN provider:
![image](https://user-images.githubusercontent.com/1952205/30395707-51dae6d2-9884-11e7-9da9-6e7ea7c310fb.png)

See [this commit](https://github.com/chrispappas007/kyarch/commit/f6ac7657b5de74bf841a7fe857ed78c34ea3d261)
