### ISSUE TITLE
Hexagon counts

### ISSUE THREAD

**Issue by chrispappas007** [chrispappas007/kyarch#6]
Something seems to be up with the hexagon counts. When I've selected the paleo sites with the slider, the legend says the site density should cap out at 8. But, when I hover over the darkest hexagons, I get some that say more than 8 (11). Look at the hexagons SW of lexington specifically.

**Comment by rgdonohue** [comment]
Yup, good catch. Semantic coding error. If we just use the same looping structure as calculating the hex total for the tooltip is should be right.

See [this commit](https://github.com/chrispappas007/kyarch/commit/d1b9181123f3647b1c8e643e01316dca6076aede)
