### ISSUE TITLE
colors of period categories and legend correspond?

### ISSUE THREAD

**Issue by rgdonohue** [chrispappas007/kyarch#8]
It may be misleading to the user to use the same colors for the periods at left with the slider as for the legend and mapped values (they don't, correct?).

Consider changing up the colors on the slider to the left?

Also, moving the legend to lower-right would help distance those classification colors from the temporal period colors at left.

**Comment by chrispappas007** [comment]
Agreed. One set of colors needs to change.

**Comment by chrispappas007** [comment]
colors changed but due to the shape of KY, I think the legend needs to stay where it is.
